# Generated by Django 5.2.1 on 2025-05-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'equifax_credit_report',
            },
        ),
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'profile_document_data',
            },
        ),
        migrations.CreateModel(
            name='EquifaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('api_category', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('id_number', models.CharField(max_length=20)),
                ('id_type', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'equifax_report',
            },
        ),
        migrations.CreateModel(
            name='EsicDtls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esic_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('employer_code', models.CharField(max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('uan_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esic_dtls',
            },
        ),
        migrations.CreateModel(
            name='GstTurnover',
            fields=[
                ('txn_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gstin', models.CharField(max_length=15)),
                ('gst_estimated_total', models.FloatField(null=True)),
                ('gst_filed_total', models.FloatField()),
                ('year', models.CharField(max_length=10)),
                ('filing_date', models.CharField(max_length=20)),
                ('pan_estimated_total', models.FloatField()),
                ('pan_filed_total', models.FloatField()),
                ('gst_status', models.CharField(max_length=50)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('register_date', models.CharField(max_length=20)),
                ('tax_payer_type', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turnover', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gst_turnover',
            },
        ),
        migrations.CreateModel(
            name='GstVerification',
            fields=[
                ('gstin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('aggregate_turn_over', models.CharField(blank=True, max_length=50)),
                ('business_constitution', models.CharField(max_length=100)),
                ('can_flag', models.CharField(blank=True, max_length=50)),
                ('central_jurisdiction', models.TextField()),
                ('compliance_rating', models.CharField(blank=True, max_length=50)),
                ('current_registration_status', models.CharField(max_length=50)),
                ('is_field_visit_conducted', models.CharField(max_length=5)),
                ('legal_name', models.CharField(max_length=255)),
                ('mandate_e_invoice', models.CharField(blank=True, max_length=50)),
                ('register_cancellation_date', models.CharField(blank=True, max_length=20)),
                ('register_date', models.CharField(max_length=20)),
                ('state_jurisdiction', models.TextField()),
                ('tax_payer_type', models.CharField(max_length=50)),
                ('trade_name', models.CharField(max_length=255)),
                ('gross_total_income', models.CharField(blank=True, max_length=50)),
                ('gross_total_income_financial_year', models.CharField(blank=True, max_length=20)),
                ('business_email', models.CharField(blank=True, max_length=100)),
                ('business_mobile', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_verification',
            },
        ),
        migrations.CreateModel(
            name='Mobile360',
            fields=[
                ('mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('txn_id', models.UUIDField(unique=True)),
                ('api_category', models.CharField(max_length=50)),
                ('api_name', models.CharField(max_length=50)),
                ('billable', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'mobile360',
            },
        ),
        migrations.CreateModel(
            name='MobileToAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('api_category', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'mobile_to_account_details',
            },
        ),
        migrations.CreateModel(
            name='ProfileAdvanceLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('api_category', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'profile_advance_lookup',
            },
        ),
        migrations.CreateModel(
            name='UanEmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'uan_employment_history',
            },
        ),
        migrations.CreateModel(
            name='UanHistoryLatestV2',
            fields=[
                ('uan', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('txn_id', models.UUIDField(unique=True)),
                ('api_category', models.CharField(max_length=50)),
                ('api_name', models.CharField(max_length=50)),
                ('billable', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('member_id', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('last_pf_submitted', models.DateField()),
            ],
            options={
                'db_table': 'uan_history_latest_v2',
            },
        ),
        migrations.CreateModel(
            name='UdyamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udyamnumber', models.CharField(db_column='registration_no', max_length=50)),
                ('txn_id', models.CharField(max_length=100)),
                ('api_category', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('enterprise_name', models.CharField(max_length=255)),
                ('organisation_type', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('social_category', models.CharField(max_length=50)),
                ('date_of_incorporation', models.DateField()),
                ('date_of_commencement', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dic', models.CharField(max_length=100)),
                ('msme_dfo', models.CharField(max_length=100)),
                ('date_of_udyam_registeration', models.DateField()),
            ],
            options={
                'db_table': 'udyam_details',
            },
        ),
        migrations.CreateModel(
            name='CIRReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cir_report_data_list', to='mobile360.creditreport')),
            ],
            options={
                'db_table': 'equifax_cir_report_data',
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('request_purpose', models.CharField(blank=True, max_length=20)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('seq', models.CharField(max_length=10)),
                ('cir_report_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_enquiry',
            },
        ),
        migrations.CreateModel(
            name='EnquirySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_12_months', models.CharField(blank=True, max_length=10)),
                ('past_24_months', models.CharField(blank=True, max_length=10)),
                ('past_30_days', models.CharField(blank=True, max_length=10)),
                ('purpose', models.CharField(blank=True, max_length=20)),
                ('recent', models.CharField(blank=True, max_length=20)),
                ('total', models.CharField(blank=True, max_length=10)),
                ('cir_report_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_summary', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_enquiry_summary',
            },
        ),
        migrations.AddField(
            model_name='creditreport',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_report', to='mobile360.equifaxreport'),
        ),
        migrations.CreateModel(
            name='BasicCreditInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('credit_score', models.CharField(blank=True, max_length=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_credit_info', to='mobile360.equifaxreport')),
            ],
            options={
                'db_table': 'equifax_basic_credit_info',
            },
        ),
        migrations.CreateModel(
            name='GstTurnoverAuthorizedSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_signatories', to='mobile360.gstturnover')),
            ],
            options={
                'db_table': 'gst_turnover_authorized_signatory',
            },
        ),
        migrations.CreateModel(
            name='GstTurnoverBusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('gst_turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_natures', to='mobile360.gstturnover')),
            ],
            options={
                'db_table': 'gst_turnover_business_nature',
            },
        ),
        migrations.CreateModel(
            name='GstFilingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=10)),
                ('taxp', models.CharField(max_length=20)),
                ('mof', models.CharField(max_length=20)),
                ('dof', models.CharField(max_length=20)),
                ('rtntype', models.CharField(max_length=10)),
                ('arn', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filing_statuses', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_filing_status',
            },
        ),
        migrations.CreateModel(
            name='GstBusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_natures', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_business_nature',
            },
        ),
        migrations.CreateModel(
            name='GstBusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saccd', models.CharField(max_length=20)),
                ('sdes', models.TextField()),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_business_detail',
            },
        ),
        migrations.CreateModel(
            name='GstBusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_nature', models.TextField()),
                ('detailed_address', models.TextField(blank=True)),
                ('last_updated_date', models.CharField(blank=True, max_length=20)),
                ('registered_address', models.TextField()),
                ('gst_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_address', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_business_address',
            },
        ),
        migrations.CreateModel(
            name='GstAuthorizedSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_signatories', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_authorized_signatory',
            },
        ),
        migrations.CreateModel(
            name='IDAndContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cir_report_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_and_contact_info', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_id_and_contact_info',
            },
        ),
        migrations.CreateModel(
            name='EmailAddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('seq', models.CharField(max_length=10)),
                ('id_and_contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_address_info', to='mobile360.idandcontactinfo')),
            ],
            options={
                'db_table': 'equifax_email_address_info',
            },
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('postal', models.CharField(blank=True, max_length=10)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('seq', models.CharField(max_length=10)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('id_and_contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_info', to='mobile360.idandcontactinfo')),
            ],
            options={
                'db_table': 'equifax_address_info',
            },
        ),
        migrations.CreateModel(
            name='IdentityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_and_contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_info', to='mobile360.idandcontactinfo')),
            ],
            options={
                'db_table': 'equifax_identity_info',
            },
        ),
        migrations.CreateModel(
            name='InquiryRequestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_purpose', models.CharField(blank=True, max_length=50)),
                ('transaction_amount', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_request_info', to='mobile360.equifaxreport')),
            ],
            options={
                'db_table': 'equifax_inquiry_request_info',
            },
        ),
        migrations.CreateModel(
            name='InquiryPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=15)),
                ('request_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_phones', to='mobile360.inquiryrequestinfo')),
            ],
            options={
                'db_table': 'equifax_inquiry_phone',
            },
        ),
        migrations.CreateModel(
            name='IDDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=10)),
                ('id_type', models.CharField(max_length=10)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('request_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_details', to='mobile360.inquiryrequestinfo')),
            ],
            options={
                'db_table': 'equifax_id_detail',
            },
        ),
        migrations.CreateModel(
            name='InquiryResponseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50)),
                ('cust_ref_field', models.CharField(blank=True, max_length=50)),
                ('report_order_no', models.CharField(blank=True, max_length=50)),
                ('success_code', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_response_header', to='mobile360.equifaxreport')),
            ],
            options={
                'db_table': 'equifax_inquiry_response_header',
            },
        ),
        migrations.CreateModel(
            name='LPGInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('gas_provider', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('consumer_mobile', models.CharField(max_length=15)),
                ('consumer_id', models.CharField(max_length=50)),
                ('consumer_status', models.CharField(max_length=50)),
                ('consumer_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('distributor_code', models.CharField(max_length=50)),
                ('distributor_name', models.CharField(max_length=255)),
                ('distributor_contact', models.CharField(max_length=50)),
                ('distributor_address', models.TextField()),
                ('mobile_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpg_info', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'lpg_info',
            },
        ),
        migrations.CreateModel(
            name='KeyHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_payment_id_name', models.CharField(max_length=255)),
                ('gas_connection_found', models.CharField(max_length=5)),
                ('connection_type', models.CharField(max_length=50)),
                ('whatsapp_business_account_status', models.CharField(max_length=50)),
                ('age_of_mobile', models.CharField(max_length=50)),
                ('active_status', models.CharField(max_length=5)),
                ('revoke_date', models.CharField(blank=True, max_length=50)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_highlights', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'key_highlights',
            },
        ),
        migrations.CreateModel(
            name='DigitalPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255, null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_payment_info', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'digital_payment_info',
            },
        ),
        migrations.CreateModel(
            name='MobileAgeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('is_ported', models.CharField(max_length=5)),
                ('mobile_age', models.CharField(max_length=50)),
                ('number_active', models.CharField(max_length=5)),
                ('number_valid', models.CharField(max_length=5)),
                ('ported_region', models.CharField(blank=True, max_length=100)),
                ('ported_telecom', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('roaming', models.CharField(max_length=5)),
                ('telecom', models.CharField(max_length=100)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_age_info', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'mobile_age_info',
            },
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ifsc', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('amount_deposited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='mobile360.mobiletoaccountdetails')),
            ],
        ),
        migrations.CreateModel(
            name='OtherId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('seq', models.CharField(max_length=10)),
                ('identity_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_ids', to='mobile360.identityinfo')),
            ],
            options={
                'db_table': 'equifax_other_id',
            },
        ),
        migrations.CreateModel(
            name='OtherKeyInd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_of_oldest_trade', models.CharField(blank=True, max_length=10)),
                ('all_lines_ever_written', models.CharField(blank=True, max_length=20)),
                ('all_lines_ever_written_in_6_months', models.CharField(blank=True, max_length=10)),
                ('all_lines_ever_written_in_9_months', models.CharField(blank=True, max_length=10)),
                ('number_of_open_trades', models.CharField(blank=True, max_length=10)),
                ('cir_report_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_key_ind', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_other_key_ind',
            },
        ),
        migrations.CreateModel(
            name='PanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=10)),
                ('document_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_documents', to='mobile360.documentdata')),
            ],
            options={
                'db_table': 'profile_pan_documents',
            },
        ),
        migrations.CreateModel(
            name='PANId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('seq', models.CharField(max_length=10)),
                ('identity_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan_ids', to='mobile360.identityinfo')),
            ],
            options={
                'db_table': 'equifax_pan_id',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('total_income', models.CharField(blank=True, max_length=20)),
                ('id_and_contact_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='mobile360.idandcontactinfo')),
            ],
            options={
                'db_table': 'equifax_personal_info',
            },
        ),
        migrations.CreateModel(
            name='PhoneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('seq', models.CharField(max_length=10)),
                ('type_code', models.CharField(blank=True, max_length=5)),
                ('id_and_contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_info', to='mobile360.idandcontactinfo')),
            ],
            options={
                'db_table': 'equifax_phone_info',
            },
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5)),
                ('inquiry_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_types', to='mobile360.inquiryphone')),
            ],
            options={
                'db_table': 'equifax_phone_type',
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('response_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_codes', to='mobile360.inquiryresponseheader')),
            ],
            options={
                'db_table': 'equifax_product_code',
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('income', models.CharField(blank=True, max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to='mobile360.profileadvancelookup')),
            ],
            options={
                'db_table': 'profile_personal_information',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('value', models.EmailField(max_length=254)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mobile360.profileadvancelookup')),
            ],
            options={
                'db_table': 'profile_emails',
            },
        ),
        migrations.AddField(
            model_name='documentdata',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_data', to='mobile360.profileadvancelookup'),
        ),
        migrations.CreateModel(
            name='AlternatePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=15)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_phones', to='mobile360.profileadvancelookup')),
            ],
            options={
                'db_table': 'profile_alternate_phones',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('date_of_reporting', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='mobile360.profileadvancelookup')),
            ],
            options={
                'db_table': 'profile_addresses',
            },
        ),
        migrations.CreateModel(
            name='RecentActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounts_deliquent', models.CharField(blank=True, max_length=10)),
                ('accounts_opened', models.CharField(blank=True, max_length=10)),
                ('accounts_updated', models.CharField(blank=True, max_length=10)),
                ('total_inquiries', models.CharField(blank=True, max_length=10)),
                ('cir_report_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_recent_activities',
            },
        ),
        migrations.CreateModel(
            name='RetailAccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('account_status', models.CharField(blank=True, max_length=50)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('balance', models.CharField(blank=True, max_length=20)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('date_reported', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('open', models.CharField(blank=True, max_length=5)),
                ('ownership_type', models.CharField(blank=True, max_length=20)),
                ('past_due_amount', models.CharField(blank=True, max_length=20)),
                ('sanction_amount', models.CharField(blank=True, max_length=20)),
                ('term_frequency', models.CharField(blank=True, max_length=20)),
                ('seq', models.CharField(max_length=10)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('cir_report_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_account_details', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_retail_account_detail',
            },
        ),
        migrations.CreateModel(
            name='History48Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_classification_status', models.CharField(blank=True, max_length=5)),
                ('payment_status', models.CharField(blank=True, max_length=5)),
                ('suit_filed_status', models.CharField(blank=True, max_length=5)),
                ('key', models.CharField(blank=True, max_length=10)),
                ('retail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_48_months', to='mobile360.retailaccountdetail')),
            ],
            options={
                'db_table': 'equifax_history_48_month',
            },
        ),
        migrations.CreateModel(
            name='RetailAccountsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_open_balance', models.CharField(blank=True, max_length=20)),
                ('most_severe_status_within_24_months', models.CharField(blank=True, max_length=50)),
                ('no_of_accounts', models.CharField(blank=True, max_length=10)),
                ('no_of_active_accounts', models.CharField(blank=True, max_length=10)),
                ('no_of_past_due_accounts', models.CharField(blank=True, max_length=10)),
                ('no_of_write_offs', models.CharField(blank=True, max_length=10)),
                ('no_of_zero_balance_accounts', models.CharField(blank=True, max_length=10)),
                ('oldest_account', models.CharField(blank=True, max_length=100)),
                ('recent_account', models.CharField(blank=True, max_length=100)),
                ('single_highest_balance', models.CharField(blank=True, max_length=20)),
                ('single_highest_credit', models.CharField(blank=True, max_length=20)),
                ('single_highest_sanction_amount', models.CharField(blank=True, max_length=20)),
                ('total_balance_amount', models.CharField(blank=True, max_length=20)),
                ('total_credit_limit', models.CharField(blank=True, max_length=20)),
                ('total_high_credit', models.CharField(blank=True, max_length=20)),
                ('total_monthly_payment_amount', models.CharField(blank=True, max_length=20)),
                ('total_past_due', models.CharField(blank=True, max_length=20)),
                ('total_sanction_amount', models.CharField(blank=True, max_length=20)),
                ('cir_report_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retail_accounts_summary', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_retail_accounts_summary',
            },
        ),
        migrations.CreateModel(
            name='RevokeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('revoke_date', models.CharField(blank=True, max_length=50)),
                ('revoke_status', models.CharField(max_length=5)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revoke_info', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'revoke_info',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='mobile360.equifaxreport')),
            ],
            options={
                'db_table': 'equifax_score',
            },
        ),
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=20)),
                ('value', models.CharField(blank=True, max_length=10)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('cir_report_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_details', to='mobile360.cirreportdata')),
            ],
            options={
                'db_table': 'equifax_score_detail',
            },
        ),
        migrations.CreateModel(
            name='ScoringElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('seq', models.CharField(max_length=10)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('score_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_elements', to='mobile360.scoredetail')),
            ],
            options={
                'db_table': 'equifax_scoring_element',
            },
        ),
        migrations.CreateModel(
            name='TelcoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('subscriber_status', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=20)),
                ('msisdn_country_code', models.CharField(max_length=5)),
                ('network_name', models.CharField(max_length=100)),
                ('network_region', models.CharField(max_length=100)),
                ('is_roaming', models.BooleanField(default=False)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telco_info', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'telco_info',
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='mobile360.uanemploymenthistory')),
            ],
            options={
                'db_table': 'company_history',
            },
        ),
        migrations.CreateModel(
            name='UdyamAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('udyam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UdyamEnterpriseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_year', models.CharField(max_length=20)),
                ('enterprise_type', models.CharField(max_length=50)),
                ('classification_date', models.DateField()),
                ('udyam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_type', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UdyamNICCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_2_digit', models.CharField(max_length=100)),
                ('nic_4_digit', models.CharField(max_length=100)),
                ('nic_5_digit', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('udyam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_code', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UdyamPlantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('udyam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_details', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='VpaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('vpa', models.CharField(max_length=100)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpa_details', to='mobile360.mobiletoaccountdetails')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('is_business', models.CharField(max_length=5)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_info', to='mobile360.mobile360')),
            ],
            options={
                'db_table': 'whatsapp_info',
            },
        ),
    ]
