# Generated by Django 4.2.20 on 2025-05-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile360Response',
            fields=[
                ('mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('txn_id', models.UUIDField(unique=True)),
                ('api_category', models.CharField(max_length=50)),
                ('api_name', models.CharField(max_length=50)),
                ('billable', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'mobile360',
            },
        ),
        migrations.CreateModel(
            name='WhatsappInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('is_business', models.CharField(max_length=5)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_info', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'whatsapp_info',
            },
        ),
        migrations.CreateModel(
            name='TelcoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('subscriber_status', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=50)),
                ('msisdn', models.CharField(max_length=20)),
                ('msisdn_country_code', models.CharField(max_length=5)),
                ('network_name', models.CharField(max_length=100)),
                ('network_region', models.CharField(max_length=100)),
                ('is_roaming', models.BooleanField(default=False)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telco_info', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'telco_info',
            },
        ),
        migrations.CreateModel(
            name='RevokeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('revoke_date', models.CharField(blank=True, max_length=50)),
                ('revoke_status', models.CharField(max_length=5)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revoke_info', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'revoke_info',
            },
        ),
        migrations.CreateModel(
            name='MobileAgeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('is_ported', models.CharField(max_length=5)),
                ('mobile_age', models.CharField(max_length=50)),
                ('number_active', models.CharField(max_length=5)),
                ('number_valid', models.CharField(max_length=5)),
                ('ported_region', models.CharField(blank=True, max_length=100)),
                ('ported_telecom', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('roaming', models.CharField(max_length=5)),
                ('telecom', models.CharField(max_length=100)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_age_info', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'mobile_age_info',
            },
        ),
        migrations.CreateModel(
            name='LPGInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('gas_provider', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('consumer_mobile', models.CharField(max_length=15)),
                ('consumer_id', models.CharField(max_length=50)),
                ('consumer_status', models.CharField(max_length=50)),
                ('consumer_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('distributor_code', models.CharField(max_length=50)),
                ('distributor_name', models.CharField(max_length=255)),
                ('distributor_contact', models.CharField(max_length=50)),
                ('distributor_address', models.TextField()),
                ('mobile_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lpg_info', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'lpg_info',
            },
        ),
        migrations.CreateModel(
            name='KeyHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital_payment_id_name', models.CharField(max_length=255)),
                ('gas_connection_found', models.CharField(max_length=5)),
                ('connection_type', models.CharField(max_length=50)),
                ('whatsapp_business_account_status', models.CharField(max_length=50)),
                ('age_of_mobile', models.CharField(max_length=50)),
                ('active_status', models.CharField(max_length=5)),
                ('revoke_date', models.CharField(blank=True, max_length=50)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_highlights', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'key_highlights',
            },
        ),
        migrations.CreateModel(
            name='DigitalPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255, null=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('center', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('mobile_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_payment_info', to='mobile360.mobile360response')),
            ],
            options={
                'db_table': 'digital_payment_info',
            },
        ),
    ]
