# Generated by Django 4.2.20 on 2025-05-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile360Response',
            new_name='Mobile360',
        ),
    ]
