# Generated by Django 4.2.20 on 2025-05-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0002_rename_mobile360response_mobile360'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsicDtls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esic_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('employer_code', models.CharField(max_length=50)),
                ('employer_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('uan_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'esic_dtls',
            },
        ),
        migrations.CreateModel(
            name='GstVerification',
            fields=[
                ('gstin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('aggregate_turn_over', models.CharField(blank=True, max_length=50)),
                ('business_constitution', models.CharField(max_length=100)),
                ('can_flag', models.CharField(blank=True, max_length=50)),
                ('central_jurisdiction', models.TextField()),
                ('compliance_rating', models.CharField(blank=True, max_length=50)),
                ('current_registration_status', models.CharField(max_length=50)),
                ('is_field_visit_conducted', models.CharField(max_length=5)),
                ('legal_name', models.CharField(max_length=255)),
                ('mandate_e_invoice', models.CharField(blank=True, max_length=50)),
                ('register_cancellation_date', models.CharField(blank=True, max_length=20)),
                ('register_date', models.CharField(max_length=20)),
                ('state_jurisdiction', models.TextField()),
                ('tax_payer_type', models.CharField(max_length=50)),
                ('trade_name', models.CharField(max_length=255)),
                ('gross_total_income', models.CharField(blank=True, max_length=50)),
                ('gross_total_income_financial_year', models.CharField(blank=True, max_length=20)),
                ('business_email', models.CharField(blank=True, max_length=100)),
                ('business_mobile', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_verification',
            },
        ),
        migrations.CreateModel(
            name='UanEmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'uan_employment_history',
            },
        ),
        migrations.CreateModel(
            name='UanHistoryLatestV2',
            fields=[
                ('uan', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('txn_id', models.UUIDField(unique=True)),
                ('api_category', models.CharField(max_length=50)),
                ('api_name', models.CharField(max_length=50)),
                ('billable', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('guardian_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('member_id', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('last_pf_submitted', models.DateField()),
            ],
            options={
                'db_table': 'uan_history_latest_v2',
            },
        ),
        migrations.CreateModel(
            name='GstFilingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=10)),
                ('taxp', models.CharField(max_length=20)),
                ('mof', models.CharField(max_length=20)),
                ('dof', models.CharField(max_length=20)),
                ('rtntype', models.CharField(max_length=10)),
                ('arn', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filing_statuses', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_filing_status',
            },
        ),
        migrations.CreateModel(
            name='GstBusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_natures', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_business_nature',
            },
        ),
        migrations.CreateModel(
            name='GstBusinessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saccd', models.CharField(max_length=20)),
                ('sdes', models.TextField()),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_business_detail',
            },
        ),
        migrations.CreateModel(
            name='GstBusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_nature', models.TextField()),
                ('detailed_address', models.TextField(blank=True)),
                ('last_updated_date', models.CharField(blank=True, max_length=20)),
                ('registered_address', models.TextField()),
                ('gst_verification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_address', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_business_address',
            },
        ),
        migrations.CreateModel(
            name='GstAuthorizedSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_signatories', to='mobile360.gstverification')),
            ],
            options={
                'db_table': 'gst_authorized_signatory',
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uan_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='mobile360.uanemploymenthistory')),
            ],
            options={
                'db_table': 'company_history',
            },
        ),
    ]
