# Generated by Django 4.2.20 on 2025-05-16 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0003_esicdtls_gstverification_uanemploymenthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstTurnover',
            fields=[
                ('txn_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gst_estimated_total', models.FloatField()),
                ('gst_filed_total', models.FloatField()),
                ('year', models.CharField(max_length=10)),
                ('filing_date', models.CharField(max_length=20)),
                ('pan_estimated_total', models.FloatField()),
                ('pan_filed_total', models.FloatField()),
                ('gst_status', models.CharField(max_length=50)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(max_length=255)),
                ('register_date', models.CharField(max_length=20)),
                ('tax_payer_type', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gst_turnover',
            },
        ),
        migrations.CreateModel(
            name='GstTurnoverBusinessNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('gst_turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_natures', to='mobile360.gstturnover')),
            ],
            options={
                'db_table': 'gst_turnover_business_nature',
            },
        ),
        migrations.CreateModel(
            name='GstTurnoverAuthorizedSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gst_turnover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_signatories', to='mobile360.gstturnover')),
            ],
            options={
                'db_table': 'gst_turnover_authorized_signatory',
            },
        ),
    ]
