# Generated by Django 4.2.20 on 2025-05-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0004_gstturnover_gstturnoverbusinessnature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstturnover',
            name='gstin',
            field=models.CharField(default='UNKNOWNGSTIN', max_length=15),
            preserve_default=False,
        ),
    ]
