# Generated by Django 4.2.20 on 2025-05-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0005_gstturnover_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstturnover',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gstturnover',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gstturnover',
            name='turnover',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
