# Generated by Django 4.2.20 on 2025-05-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0006_gstturnover_last_updated_gstturnover_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstturnover',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='gstturnover',
            name='source',
        ),
        migrations.RemoveField(
            model_name='gstturnover',
            name='turnover',
        ),
    ]
