# Generated by Django 4.2.20 on 2025-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0008_gstturnover_last_updated_gstturnover_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstturnover',
            name='gst_estimated_total',
            field=models.FloatField(null=True),
        ),
    ]
