# Generated by Django 4.2.20 on 2025-05-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0009_alter_gstturnover_gst_estimated_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdyamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100)),
                ('api_category', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField(default=True)),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('enterprise_name', models.CharField(max_length=255)),
                ('organisation_type', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('social_category', models.CharField(max_length=50)),
                ('date_of_incorporation', models.DateField()),
                ('date_of_commencement', models.DateField()),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dic', models.CharField(max_length=100)),
                ('msme_dfo', models.CharField(max_length=100)),
                ('date_of_udyam_registeration', models.DateField()),
            ],
            options={
                'db_table': 'udyam_details',
            },
        ),
        migrations.CreateModel(
            name='UdyamPlantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('udyam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_details', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UdyamNICCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic_2_digit', models.CharField(max_length=100)),
                ('nic_4_digit', models.CharField(max_length=100)),
                ('nic_5_digit', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('udyam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic_code', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UdyamEnterpriseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_year', models.CharField(max_length=20)),
                ('enterprise_type', models.CharField(max_length=50)),
                ('classification_date', models.DateField()),
                ('udyam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_type', to='mobile360.udyamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UdyamAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('udyam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='mobile360.udyamdetails')),
            ],
        ),
    ]
