# Generated by Django 4.2.20 on 2025-05-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0010_udyamdetails_udyamplantdetail_udyamniccode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udyamdetails',
            name='udyamnumber',
            field=models.CharField(db_column='registration_no', default='PLACEHOLDER', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='udyamdetails',
            name='billable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='udyamdetails',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
