# Generated by Django 4.2.20 on 2025-05-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0011_udyamdetails_udyamnumber_alter_udyamdetails_billable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udyamdetails',
            name='udyamnumber',
            field=models.CharField(db_column='registration_no', max_length=50),
        ),
    ]
