# Generated by Django 4.2.20 on 2025-05-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile360', '0012_alter_udyamdetails_udyamnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileToAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=100, unique=True)),
                ('api_category', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=100)),
                ('billable', models.BooleanField()),
                ('message', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'mobile_to_account_details',
            },
        ),
        migrations.CreateModel(
            name='VpaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('vpa', models.CharField(max_length=100)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpa_details', to='mobile360.mobiletoaccountdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ifsc', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('amount_deposited', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='mobile360.mobiletoaccountdetails')),
            ],
        ),
    ]
