# Generated by Django 4.2.20 on 2025-06-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='email',
            field=models.EmailField(max_length=320, unique=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=1024),
        ),
    ]
