# Generated by Django 4.2.20 on 2025-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_gstverificationreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTTurnoverReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_no', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=9)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('gst_no', 'year')},
            },
        ),
    ]
