# Generated by Django 4.2.20 on 2025-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_profileadvancereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquifaxV3Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('id_type', models.CharField(max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
