# Generated by Django 4.2.20 on 2025-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_equifaxv3report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='udyamreport',
            name='id',
        ),
        migrations.AlterField(
            model_name='udyamreport',
            name='registration_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
