# Generated by Django 4.2.20 on 2025-05-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_remove_udyamreport_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equifaxv3report',
            name='id',
        ),
        migrations.AlterField(
            model_name='equifaxv3report',
            name='id_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equifaxv3report',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
