# Generated by Django 4.2.20 on 2025-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0011_mobiletoaccountnumber_mobiletodllookup_uanwithoutotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanAllInOne',
            fields=[
                ('pan_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
