# Generated by Django 4.2.20 on 2025-06-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_digitalpaymentanalyser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakOSINT',
            fields=[
                ('request_body', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
