# Generated by Django 4.2.20 on 2025-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_leakosint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterFind',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HunterVerify',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
