# Generated by Django 5.2.1 on 2025-05-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CORPORATE', 'Corporate'), ('DEVELOPER', 'Developer'), ('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
