# Generated by Django 5.2.1 on 2025-06-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='sessionStartTime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='lastLogin',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='sessionEndTime',
        ),
        migrations.AddField(
            model_name='usersession',
            name='latitude',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='usersession',
            name='longitude',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
