# Generated by Django 5.2.1 on 2025-06-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HudsonRockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stealer', models.CharField(max_length=255)),
                ('stealerFamily', models.CharField(max_length=255)),
                ('dateUploaded', models.DateTimeField()),
                ('employeeAt', models.JSONField()),
                ('clientAt', models.JSONField()),
                ('dateCompromised', models.DateTimeField()),
                ('ip', models.CharField(max_length=50)),
                ('computerName', models.CharField(max_length=255)),
                ('operatingSystem', models.CharField(max_length=255)),
                ('malwarePath', models.CharField(max_length=255)),
                ('antiviruses', models.JSONField()),
                ('credentials', models.JSONField()),
                ('data_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'hudson_rock_data',
            },
        ),
    ]
